version: "3.2"
services:
  backend:
    container_name: decentverse-backend
    build:
      context: ../../dist/apps/backend
      dockerfile: ../../apps/backend/Dockerfile
    network_mode: host
    command: node main.js --max-old-space-size=8192
    restart: unless-stopped
    environment:
      - ENVIRONMENT=ayias
    deploy:
      replicas: 1