import { Schema, Types, FilterQuery } from "mongoose";
import * as DataLoader from "dataloader";
export type ID = Schema.Types.ObjectId;
export const ObjectId = Schema.Types.ObjectId;
export { FilterQuery as Query };
export { DataLoader };
export * from "../dbConfig";
export * as Admin from "./admin/admin.model";
export * as User from "./user/user.model";
export * as Asset from "./asset/asset.model";
export * as Character from "./character/character.model";
export * as Map from "./map/map.model";
export * as File from "./file/file.model";
