version: "3.2"
services:
  frontend: 
    container_name: decentverse-frontend
    network_mode: host
    restart: unless-stopped
    environment:
      - ENVIRONMENT=ayias
    deploy:
      replicas: 1