version: "3.2"
services:
  frontend: 
    container_name: decentverse-frontend
    build:
      context: ../../dist/apps/frontend
      dockerfile: ../../../apps/frontend/Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - ENVIRONMENT=ayias
    deploy:
      replicas: 1