// export * from "./scalar.type";
export * from "./admin/admin.gql";
export * from "./asset/asset.gql";
export * from "./character/character.gql";
export * from "./dialog/dialog.gql";
export * from "./editor/editor.gql";
// export * from "./game/game.types";
export * from "./map/map.gql";
export * from "./user/user.gql";
export * from "./world/world.gql";
